import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTypeAndAddressModules1788418198550 implements MigrationInterface {
    name = 'AddTypeAndAddressModules1788418198550'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`countries\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`iso_code\` varchar(2) NOT NULL, \`calling_code\` varchar(8) NOT NULL, \`subdivisions\` json NOT NULL, \`all_sub\` json NOT NULL, \`code\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_31d60a54633e88225b40081e18\` (\`iso_code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`regions\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`parent_sub\` varchar(255) NULL, \`country_id\` varchar(255) NOT NULL, \`code\` varchar(255) NOT NULL, INDEX \`IDX_88710f9af21f62e1bf43bbce75\` (\`country_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`zones\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`parent_sub\` varchar(255) NULL, \`region_id\` varchar(255) NOT NULL, \`code\` varchar(255) NOT NULL, INDEX \`IDX_03a8bf075883088d93c167de3f\` (\`region_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`villages\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('VILLAGE', 'NEIGHBORHOOD') NOT NULL, \`parent_sub\` varchar(255) NULL, \`zone_id\` varchar(255) NOT NULL, \`code\` varchar(255) NOT NULL, INDEX \`IDX_ce06d3a030176d175ac686195c\` (\`zone_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`first_name\` varchar(255) NULL, \`last_name\` varchar(255) NULL, \`email\` varchar(255) NULL, \`image_profile\` varchar(255) NULL, \`password\` varchar(255) NULL, \`google_id\` varchar(255) NULL, \`pin_code\` text NULL, \`status\` enum ('active', 'unverified', 'disabled', 'blocked', 'deleted') NOT NULL DEFAULT 'unverified', \`roles\` set ('user', 'agent', 'investor', 'manager', 'admin', 'engineer') NOT NULL DEFAULT 'user', \`code\` varchar(255) NOT NULL, \`id_country\` varchar(255) NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_0bd5012aeb82628e07f6a1be53\` (\`google_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_devices\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NOT NULL, \`device_fingerprint\` varchar(64) NOT NULL, \`device_name\` varchar(255) NULL, \`device_type\` enum ('mobile', 'desktop', 'tablet', 'unknown') NULL DEFAULT 'unknown', \`os\` varchar(255) NULL, \`browser\` varchar(255) NULL, \`fcm_token\` text NULL, \`last_active_at\` datetime NULL, INDEX \`IDX_28bd79e1b3f7c1168f0904ce24\` (\`user_id\`), UNIQUE INDEX \`IDX_f75ac6098cb66552fd9a389157\` (\`device_fingerprint\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_sessions\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NOT NULL, \`device_fingerprint\` varchar(64) NOT NULL, \`refresh_token_hash\` varchar(64) NOT NULL, \`expires_at\` datetime NOT NULL, \`last_active_at\` datetime NOT NULL, \`ip\` varchar(45) NULL, INDEX \`IDX_e9658e959c490b0a634dfc5478\` (\`user_id\`), UNIQUE INDEX \`IDX_cc132fa5f7a96610010e293e52\` (\`refresh_token_hash\`), UNIQUE INDEX \`IDX_e5830a23e1f7e90d7ccb20ad9a\` (\`user_id\`, \`device_fingerprint\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_conversations\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`subject_type\` varchar(255) NULL, \`subject_id\` varchar(255) NULL, \`status\` enum ('OPEN', 'PENDING', 'RESOLVED', 'CLOSED') NOT NULL DEFAULT 'OPEN', \`mode\` enum ('BOT', 'AGENT') NOT NULL DEFAULT 'AGENT', \`last_message_at\` datetime NULL, \`last_message_preview\` varchar(255) NULL, \`last_message_sender_id\` varchar(255) NULL, \`closed_at\` datetime NULL, INDEX \`IDX_0d93caa64c1985b786d3cf4fa6\` (\`last_message_at\`), INDEX \`IDX_0025fe6d8a01cb94c437346c50\` (\`subject_type\`, \`subject_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_messages\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`conversation_id\` varchar(255) NOT NULL, \`sender_id\` varchar(255) NULL, \`sender_type\` enum ('HUMAN', 'AI', 'SYSTEM') NOT NULL, \`kind\` enum ('TEXT', 'MEDIA', 'CALL', 'SYSTEM') NOT NULL DEFAULT 'TEXT', \`body\` longtext NULL, \`reply_to\` varchar(255) NULL, \`delivered_at\` datetime NULL, \`read_at\` datetime NULL, \`failed_at\` datetime NULL, \`content_deleted_at\` datetime NULL, INDEX \`IDX_bdfd8165e694fe9d3ce4140c87\` (\`conversation_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_attachments\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`message_id\` varchar(255) NOT NULL, \`kind\` enum ('IMAGE', 'AUDIO', 'VIDEO', 'FILE') NOT NULL, \`url\` varchar(255) NOT NULL, \`meta\` longtext COLLATE "utf8mb4_bin" NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_participants\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`conversation_id\` varchar(255) NOT NULL, \`actor_id\` varchar(255) NOT NULL, \`actor_type\` enum ('HUMAN', 'AI', 'SYSTEM') NOT NULL, \`role\` enum ('OWNER', 'MEMBER', 'ASSIGNED_AGENT', 'CLIENT', 'DRIVER') NOT NULL, \`joined_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`left_at\` datetime NULL, \`last_read_at\` datetime NULL, INDEX \`IDX_fb3a8029a2688a74971e918df7\` (\`conversation_id\`), INDEX \`IDX_14c4a121a12bc2d8514c1a12f4\` (\`actor_id\`, \`left_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contact_messages\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`subject\` varchar(255) NULL, \`message\` text NOT NULL, \`status\` enum ('new', 'read', 'treated') NOT NULL DEFAULT 'new', \`admin_note\` text NULL, \`ip\` varchar(255) NULL, \`read_at\` datetime NULL, \`answered_at\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`faqs\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`question\` text NOT NULL, \`answer\` text NULL, \`category\` enum ('general', 'account', 'billing', 'security', 'technical') NULL, \`sort_order\` int NOT NULL DEFAULT '0', \`answered_at\` datetime NULL, \`hidden_at\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`key\` varchar(255) NOT NULL, \`value\` text NULL, \`type\` enum ('string', 'number', 'boolean', 'json') NOT NULL DEFAULT 'string', \`category\` varchar(255) NULL, \`label\` varchar(255) NULL, \`description\` text NULL, \`is_public\` tinyint NOT NULL DEFAULT 0, \`is_editable\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_c8639b7626fa94ba8265628f21\` (\`key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mail_failed_jobs\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`type\` enum ('confirm-email', 'reset-password', 'reset-pin', 'reset-link', 'contact-notify', 'contact-ack') NOT NULL, \`to\` varchar(255) NOT NULL, \`payload\` json NOT NULL, \`last_error\` text NULL, \`attempts\` int NOT NULL DEFAULT '0', \`status\` enum ('pending', 'abandoned') NOT NULL DEFAULT 'pending', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NULL, \`type\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`body\` text NOT NULL, \`data\` json NULL, \`dedup_key\` varchar(255) NOT NULL, \`expires_at\` datetime NULL, \`read_at\` datetime NULL, INDEX \`IDX_9a8a82462cab47c73d25f49261\` (\`user_id\`), INDEX \`IDX_aef1c7aef3725068e5540f8f00\` (\`type\`), UNIQUE INDEX \`IDX_4b9358d8a649bfbd1aac36de71\` (\`dedup_key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notification_states\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`user_id\` varchar(255) NOT NULL, \`notification_id\` varchar(255) NOT NULL, \`seen_at\` datetime NULL, \`read_at\` datetime NULL, \`dismissed_at\` datetime NULL, UNIQUE INDEX \`IDX_84259a57dcebe77e5b8a03febe\` (\`user_id\`, \`notification_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`types\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` varchar(255) NULL, \`updated_by\` varchar(255) NULL, \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`scope\` enum ('INTENTION', 'SACRAMENT', 'DONATION', 'PUBLICATION', 'SCHEDULE') NOT NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`code\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_a085d888aeedcc6857537cd485\` (\`scope\`, \`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`regions\` ADD CONSTRAINT \`FK_88710f9af21f62e1bf43bbce751\` FOREIGN KEY (\`country_id\`) REFERENCES \`countries\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`zones\` ADD CONSTRAINT \`FK_03a8bf075883088d93c167de3f6\` FOREIGN KEY (\`region_id\`) REFERENCES \`regions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`villages\` ADD CONSTRAINT \`FK_ce06d3a030176d175ac686195c1\` FOREIGN KEY (\`zone_id\`) REFERENCES \`zones\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_devices\` ADD CONSTRAINT \`FK_28bd79e1b3f7c1168f0904ce241\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` ADD CONSTRAINT \`FK_e9658e959c490b0a634dfc54783\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` ADD CONSTRAINT \`FK_f2b45e7d39891a95f44bb89f4ea\` FOREIGN KEY (\`device_fingerprint\`) REFERENCES \`user_devices\`(\`device_fingerprint\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` ADD CONSTRAINT \`FK_3d623662d4ee1219b23cf61e649\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`chat_conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` ADD CONSTRAINT \`FK_4bc3858c999f505ec775f1a7a8c\` FOREIGN KEY (\`reply_to\`) REFERENCES \`chat_messages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_attachments\` ADD CONSTRAINT \`FK_36f9810618284e1e269eeedaefd\` FOREIGN KEY (\`message_id\`) REFERENCES \`chat_messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_participants\` ADD CONSTRAINT \`FK_fb3a8029a2688a74971e918df79\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`chat_conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification_states\` ADD CONSTRAINT \`FK_68c0fb79b17b3a38c597760f2dc\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notification_states\` ADD CONSTRAINT \`FK_d5947be1c8ddf16bd27b47d05fd\` FOREIGN KEY (\`notification_id\`) REFERENCES \`notifications\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`notification_states\` DROP FOREIGN KEY \`FK_d5947be1c8ddf16bd27b47d05fd\``);
        await queryRunner.query(`ALTER TABLE \`notification_states\` DROP FOREIGN KEY \`FK_68c0fb79b17b3a38c597760f2dc\``);
        await queryRunner.query(`ALTER TABLE \`chat_participants\` DROP FOREIGN KEY \`FK_fb3a8029a2688a74971e918df79\``);
        await queryRunner.query(`ALTER TABLE \`chat_attachments\` DROP FOREIGN KEY \`FK_36f9810618284e1e269eeedaefd\``);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` DROP FOREIGN KEY \`FK_4bc3858c999f505ec775f1a7a8c\``);
        await queryRunner.query(`ALTER TABLE \`chat_messages\` DROP FOREIGN KEY \`FK_3d623662d4ee1219b23cf61e649\``);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` DROP FOREIGN KEY \`FK_f2b45e7d39891a95f44bb89f4ea\``);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` DROP FOREIGN KEY \`FK_e9658e959c490b0a634dfc54783\``);
        await queryRunner.query(`ALTER TABLE \`user_devices\` DROP FOREIGN KEY \`FK_28bd79e1b3f7c1168f0904ce241\``);
        await queryRunner.query(`ALTER TABLE \`villages\` DROP FOREIGN KEY \`FK_ce06d3a030176d175ac686195c1\``);
        await queryRunner.query(`ALTER TABLE \`zones\` DROP FOREIGN KEY \`FK_03a8bf075883088d93c167de3f6\``);
        await queryRunner.query(`ALTER TABLE \`regions\` DROP FOREIGN KEY \`FK_88710f9af21f62e1bf43bbce751\``);
        await queryRunner.query(`DROP INDEX \`IDX_a085d888aeedcc6857537cd485\` ON \`types\``);
        await queryRunner.query(`DROP TABLE \`types\``);
        await queryRunner.query(`DROP INDEX \`IDX_84259a57dcebe77e5b8a03febe\` ON \`notification_states\``);
        await queryRunner.query(`DROP TABLE \`notification_states\``);
        await queryRunner.query(`DROP INDEX \`IDX_4b9358d8a649bfbd1aac36de71\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_aef1c7aef3725068e5540f8f00\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a8a82462cab47c73d25f49261\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`mail_failed_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8639b7626fa94ba8265628f21\` ON \`settings\``);
        await queryRunner.query(`DROP TABLE \`settings\``);
        await queryRunner.query(`DROP TABLE \`faqs\``);
        await queryRunner.query(`DROP TABLE \`contact_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_14c4a121a12bc2d8514c1a12f4\` ON \`chat_participants\``);
        await queryRunner.query(`DROP INDEX \`IDX_fb3a8029a2688a74971e918df7\` ON \`chat_participants\``);
        await queryRunner.query(`DROP TABLE \`chat_participants\``);
        await queryRunner.query(`DROP TABLE \`chat_attachments\``);
        await queryRunner.query(`DROP INDEX \`IDX_bdfd8165e694fe9d3ce4140c87\` ON \`chat_messages\``);
        await queryRunner.query(`DROP TABLE \`chat_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_0025fe6d8a01cb94c437346c50\` ON \`chat_conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_0d93caa64c1985b786d3cf4fa6\` ON \`chat_conversations\``);
        await queryRunner.query(`DROP TABLE \`chat_conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_e5830a23e1f7e90d7ccb20ad9a\` ON \`user_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_cc132fa5f7a96610010e293e52\` ON \`user_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_e9658e959c490b0a634dfc5478\` ON \`user_sessions\``);
        await queryRunner.query(`DROP TABLE \`user_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_f75ac6098cb66552fd9a389157\` ON \`user_devices\``);
        await queryRunner.query(`DROP INDEX \`IDX_28bd79e1b3f7c1168f0904ce24\` ON \`user_devices\``);
        await queryRunner.query(`DROP TABLE \`user_devices\``);
        await queryRunner.query(`DROP INDEX \`IDX_0bd5012aeb82628e07f6a1be53\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce06d3a030176d175ac686195c\` ON \`villages\``);
        await queryRunner.query(`DROP TABLE \`villages\``);
        await queryRunner.query(`DROP INDEX \`IDX_03a8bf075883088d93c167de3f\` ON \`zones\``);
        await queryRunner.query(`DROP TABLE \`zones\``);
        await queryRunner.query(`DROP INDEX \`IDX_88710f9af21f62e1bf43bbce75\` ON \`regions\``);
        await queryRunner.query(`DROP TABLE \`regions\``);
        await queryRunner.query(`DROP INDEX \`IDX_31d60a54633e88225b40081e18\` ON \`countries\``);
        await queryRunner.query(`DROP TABLE \`countries\``);
    }

}
